### PR TITLE
Update absolute links to relative

### PR DESCRIPTION
**Pull request by Saisang**

### CODE REVIEW

**Comment by Saisang** [comment]
#sign-off

**Review by carlyrevier — CHANGES_REQUESTED** [review]

**Comment by carlyrevier** [comment]
@Saisang - Can you please update as requested above?

**Comment by Saisang** [comment]
> @Saisang - Can you please update as requested above?

Those links are all working. You see them broken because you are in the review site. So it jumps to a review site. https://review.learn.microsoft.com/en-us/users/georgechrysovalantisgrammatikos-8518/ When it published to live that would be good and jump to correct link.

**Comment by carlyrevier** [comment]
> > @Saisang - Can you please update as requested above?
> 
> Those links are all working. You see them broken because you are in the review site. So it jumps to a review site. https://review.learn.microsoft.com/en-us/users/georgechrysovalantisgrammatikos-8518/ When it published to live that would be good and jump to correct link.

Interesting...I could have sworn I tested this before and it didn't work, but I could be thinking of something else. I'll merge this. Thanks again for doing this work!

**Review by carlyrevier — APPROVED** [review]

**Pull request merged**
